version: 1

weekdays:
    open-time   :     11:00   #
    open-offset :     60      # in minutes
    setup-time  :     35      # in minutes
    close-time  :     23:00

weekends:
    open-time   :     10:30
    open-offset :     60      # in minutes
    setup-time  :     35      # in minutes
    close-time  :     23:30

