version: 1

days            :     1

weekday:
    open-hr  :    11   #
    open-min   :    00   #
    open-offset     :    60   # in minutes
    setup-time      :    35   # in minutes
    close-hr :    23
    close-min  :    00

weekend:
    open-hr  :    10   #
    open-min   :    30   #
    open-offset     :    60   # in minutes
    setup-time      :    35   # in minutes
    close-hr :    23
    close-min  :    30

